uid: gbicskei:audiogroup_leader_checker
label: Google Chromecast Audiogroup Configurator
description: When a chromecast:audiogroup sink ...
configDescriptions:
  - name: thingId
    type: TEXT
    label: Thing id
    context: thing
    required: true
    description: Id of the thing of type chromecast:audiogroup
  - name: audioGroupName
    type: TEXT
    label: Device Group Id
    context: tag
    required: true
    description: Name of the device group is Google Home app
triggers:
  - id: "1"
    label: Chromecast:audiogroup Thing changes to OFFLINE
    configuration:
      thingUID: "{{thingId}}"
      status: OFFLINE
      previousStatus: ONLINE
    type: core.ThingStatusChangeTrigger
conditions: []
actions:
  - inputs: {}
    id: "2"
    configuration:
      type: application/javascript;version=ECMAScript-2021
      script: >
        console.loggerName = 'aaa';
        console.log('AAA');
    type: script.ScriptAction
